

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    volumes:
    - ./.:/app/.
    networks:
    - app-go
networks:
  app-go:
    driver: bridge